version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - db
    networks:
      - laravel

  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: codebayan
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    container_name: 'phpmyadmin'
    restart: always
    depends_on:
      - db
    ports:
      - 9091:80
    environment:
      - PMA_ARBITRARY=1  
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./docker/php/phpv2.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  composer:
    image: composer:2
    container_name: composer
    volumes:
      - ./src:/var/www/html
    user: "1000:1000"
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:18.16.0
    container_name: npm
    volumes:
      - ./src:/var/www/html
    user: "1000:1000"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel